# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions: 
  contents: read
  actions: read
  checks: write

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Cache NuGet packages
      uses: actions/cache@v4
      with:
        path: ${{ env.NUGET_PACKAGES }}
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj', '**/*.fsproj', '**/*.vbproj', '**/Directory.Packages.props', '**/nuget.config', '**/*.sln', '**/*.slnx') }}
        restore-keys: |
            ${{ runner.os }}-nuget-
                
    - name: Restore
      run: dotnet restore Mercator.slnx
      
    - name: Build (Release)
      run: dotnet build Mercator.slnx --configuration Release --no-restore
      
    - name: Test (Release) + TRX
      run: dotnet test Mercator.slnx --configuration Release --no-build --verbosity normal --logger "trx" --results-directory ./TestResults

    - name: Test Report (GitHub UI)
      if: always()
      uses: dorny/test-reporter@v1
      with:
          name: Tests
          path: ./TestResults/**/*.trx
          reporter: dotnet-trx
          fail-on-error: false
